[package]
name = "ci-learn"
version = "0.1.0"
authors = ["DinhVanDungYknb <dungdv@youmed.vn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
